### ISSUE TITLE
5v från HAN-port, 3v på Pico?!

### ISSUE THREAD

**Issue by speedbird620** [HenrikSolver/picowhanport#3]
Hej @HenrikSolver,

Jag tolkar din skiss som att Data UT (PIN5 på RJ12) går till PIN7 på Pico:n. 

![PICO_HAN](https://github.com/HenrikSolver/picowhanport/assets/50543575/3f1f06ef-83a9-4506-82f7-1c656dc0e2e5)

Då processorn på PI Pico arbetar med 3 volt och HAN-portens utgång är på 5 volt, är detta inte enligt spec. Jag är rädd för att det finns risk finns att Picon pajar i längden. 

En annan sak jag funderar på, när jag läser på forum så ska Data UT inverteras för att microprocessorn ska läsa informationen. I din design finns inte det inkluderat. Är detta något du löser i mjukvaran?

/mik

**Comment by HenrikSolver** [comment]
Hej @speedbird620 . 
Tack för din fråga.
DataOut från  elmätaren är open collector och matas från 3,3v via 3k motståndet som nämns i instruktionerna, så det borde funka. Inventeringen löses i mjukvaran. Eller egentligen  genom att konfigurera UARTen så den inverterar signalen. Jag borde naturligtvis skapat ett ordentligt schema, men om du ritar in ett motstånd mellan pinne 7 (GP5) och 36 (3v3) i ditt så får du gärna bidra med det.
/Henrik

**Comment by speedbird620** [comment]
Rgr. Då är jag med. Tack för svar.

Stämmer denna skiss?

![image](https://github.com/HenrikSolver/picowhanport/assets/50543575/6190399e-d1ea-4ae6-8412-d38b41d47094)

**Comment by HenrikSolver** [comment]
Ser bra ut. Vill du göra en PR på README filen för att lägga till skissen? Om du tycker det krångligt kan jag göra det själv (med en hänvisning till dig förstås) det tar mig inte så många minuter.

**Comment by speedbird620** [comment]
Nu är jag inte direkt en fena på GitHub, så jag har ingen aning om hur man gör en PR. Om du vill så får du gärna återanvända skissen jag gjorde. Du behöver inte lämna någon referens.

**Comment by gurka** [comment]
Hej,

Tänkte att jag kunde ställa lite frågor relaterat till skissen här istället för att göra en ny issue.

- Visst har det försvunnit i nya skissen att DataREQ ska kopplas mot VCC på RJ12:an?
- På tal om DataREQ: är det OK att koppla ihop denna med VCC direkt eller bör det sitta en resistor mellan? Aidon har skrivit så här i deras manual: `Ingång för databegäran är avsedd att sänka strömmen med 4,0–10,0 mA när den aktiveras`, men jag är inte säker på vad det innebär. Menar dom att det sitter en resistor eller motsvarande innanför HAN-porten?
- Spelar det någon roll att man bara kopplar GND från RJ12 till en GND-pinne på pico:n, som i andra skissen, eller bör man koppla den mot alla GND-pinnar som i första skissen?

**Comment by HenrikSolver** [comment]
Halloj Gurka.

1. Det står i och för sig i tabellen att de skall kopplas ihopa, men jag håller med om att det kanske inte är supertydligt.
2. Den mest detaljerade informationen jag kan hitta på interfacet är [denna](https://www.netbeheernederland.nl/sites/default/files/2024-02/dsmr_5.0.2_p1_companion_standard.pdf). I schemat på sidan 7 sitter det ett motstånd mellan optokopplaren och data_request. Det verkar vettigt att det gör det för att skydda mätaren.
3. Det verkar inte spela någon roll, jag har bara kopplat in GND till en pinne, och det har fungerat fint.

Henrik

**Comment by gurka** [comment]
Aha, så DataREQ och dess optokopplare blir då, mer eller mindre, som som en enkel LED seriekopplad med en resistor. 4mA-10mA är den ström som krävs för att driva denna optokopplare / LED.

Ska bli spännande att se om jag kan få till en fungerande läsare. Just nu verkar dock Pico W vara slutsåld hos de flesta återförsäljare, så vi får se när det blir.

Tack för svar!

**Comment by gurka** [comment]
Jag har nog inte helt förstått hur optokopplaren och open collector fungerar.

Det sitter en LED och en transistor i optokopplaren. När LED:en lyser så blir DATA och DATA_GND sammankopplade via transistorn och man kan läsa ut 0V (low) på DATA? När LED:en inte lyser så bryts kopplingen mellan DATA och DATA_GND, och man kan istället läsa ut 3,3V (high) på DATA, som kommer via resistorn och 3v3?

Är det denna "invertering" (LED på => low på GP5, LED av => high på GP5) som gör att man sen måste invertera tillbaka i mjukvaran / UARTen?

Hur pass stämmer denna beskrivning?

Egentligen undrar jag hur man kom fram till just 3k Ohm och om t.ex. 2k Ohm eller 4k Ohm skulle fungera lika bra, då det är såna jag har hemma :)

**Comment by HenrikSolver** [comment]
Halloj gurka.

Det verkar som du förstått hur open collector funkar :-). Valet av motstånd är inte mer vetenskapligt än jag hade sådana i lådan och det funkade. Det nederländska dokumentet säger "From an OSM perspective, the maximum current flowing towards the “Data” line must not exceed 5 mA.". Så det funkar säkert med både 2k och 4k motstånd

**Comment by gurka** [comment]
Nu har jag testat mjukvaran och den fungerar perfekt. Det enda jag hade problem med i början var att det var för långt mellan pico:n/elmätaren och access-punkten vilket gjorde att pico:n hade svårt att ansluta till wifi. Till slut lyckades den ansluta och jag kunde se att mqtt-brokern tog emot meddelanden, men direkt jag stängde dörren till elskåpet så tappade den anslutningen.

Jag har löst det temporärt nu genom att en extra AP närmare elskåpet, men en sak jag noterade när pico:n hade problem att ansluta var att den aldrig riktigt lyckades åter-ansluta av sig själv. Jag var tvungen att koppla ur den ur elmätaren och starta om den på så sätt för att den skulle kunna ansluta igen. Jag funderar på om det har med `machine.reset` vs. `machine.soft_reset` att göra?

Som koden ser ut nu så gör man ju en hard reset om wifi-anslutningen skulle misslyckas. Lyckas wifi-anslutningen men kommunikation mot mqtt misslyckas så gör man istället en soft reset, och detta kanske är OK om mqtt misslyckas på grund av att t.ex. brokern är offline. Men om mqtt misslyckas på grund av att den har tappat wifi så kanske man borde göra en hard reset istället?

Med andra ord, man kanske alltid ska göra en hard reset vid fel, för att säkerställa att allting sätts upp korrekt igen?
